docs: Hint on linebreaks in multiline help strings
ajalt/clikt pull request #376
Opened 2022-11-28 15:23 UTC by timmc

`\u0085` in a multiline help string will be printed verbatim, so suggest using interpolation to insert this character.

2022-11-28 17:45 UTC, ajalt requested changes

2022-11-28 17:45 UTC, ajalt commented on docs/documenting.md
> +
```suggestion
!!! tip

    In multiline strings (which do not parse escape sequences) you'll need to insert the literal
    in a different way, such as with `${"\u0085"}`.
```

This is a helpful tip, let's put it in an [admonition box](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#type:tip)

2022-11-28 18:55 UTC, timmc commented on docs/documenting.md
> +
Ah, nice.

2022-12-03 17:38 UTC, ajalt approved these changes

2022-12-03 19:05 UTC, merged

2022-12-03 19:06 UTC, ajalt commented
Thanks!